export default  {
  ADD_NOTE: 'ADD_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',

  SET_INPUT_ADDR: 'SET_INPUT_ADDR',
  SET_INPUT_NAME:'SET_INPUT_NAME',
  SET_INPUT_PHN:'SET_INPUT_PHN',
  SET_INPUT_DEG:'SET_INPUT_DEG',
	SET_INPUT_EMAIL:'SET_INPUT_EMAIL',
  SET_INPUT_SALARY: 'SET_INPUT_SALARY',
  SET_INPUT_ID: 'SET_INPUT_ID',
  RESET_INPUT: 'RESET_INPUT',
}